#General Hyper Parameters:
gpu_id: 3
use_gpu: True
seed: 42
#device: cuda:2
#save_dataset: True

#Training Hyper Parameters:
epochs: 200
train_batch_size: 256
embedding_size: 64
hidden_size: 64
#train_batch_size: 512
learner: adam
#learning_rate: 1e-3
#neg_sampling: None
#neg_sampling: {'popularity': 1}
eval_step: 1
stopping_step: 10
clip_grad_norm: {'max_norm': 5.0, 'norm_type': 2}
weight_decay: 1e-4

# scheduler
scheduler: False
step_size: 5
gamma: 0.1

#Evaluation Hyper Parameters:
eval_args:
  group_by: user
  order: TO
  split: {'LS': 'valid_and_test'}
  mode: 'full'
neg_sampling: None
repeatable: True
#metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
metrics: ['Hit', 'NDCG']

topk: [10]
valid_metric: NDCG@10
valid_metric_bigger: True
eval_batch_size: 256
metric_decimal_place: 4

#Dataset Hyper Parameters:
rm_dup_inter: first
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
BEHAVIOR_ID_FIELD: behavior_type

#field_separator: '\t'
#seq_separator: ' '


#Other Hyper Parameters:
dropout_prob: 0.3
loss_type: 'CE'
initializer_range: 0.02
step: 1
behavior_num: 2
